### ISSUE TITLE
p.210 cybozu.co.jpのSCT名

### ISSUE THREAD

**Issue by myakura** [herumi/anninbon#1]
こんにちは。初版 第2刷を読んでおります。

p.210 5行目の文で、cybozu.co.jpのSCTに対する言及として

> cybozu.co.jpのSCTは「Googole "Argon2022"」と「DigiCert Yeti2022」の2箇所で発行されたSCTを示しています。

とありますが、「Googole」は「Google」のタイポかと思われます。

**Comment by herumi** [comment]
ご指摘ありがとうございます。
正誤表を更新しました。
https://github.com/herumi/anninbon/commit/fdea9d9e9ccc2e130d4d579b0b42179992001e42

**Comment by myakura** [comment]
ありがとうございます！
